/**
 * Server-side persistent store for AI-generated contact profile overrides.
 *
 * When Michael clicks "Generate profile with Basil" on a contact, the resulting
 * personality/whatMakesThemTick/watchOut fields are stored here rather than in
 * localStorage so:
 *   - The drafter (lib/events/drafter.ts) can use enriched profiles when
 *     composing replies, rather than falling back to the seed profile only.
 *   - Meeting prep can incorporate the latest AI read on an attendee.
 *   - The system prompt persona summaries can reflect current AI knowledge.
 *
 * Only fields regenerated by AI are overridden.  The base Contact record in
 * lib/contacts-data.ts remains the canonical source for everything else.
 */

import type { ProfileOverride } from "@/lib/contact-profile-overrides";
import { readUserStore, writeUserStore } from "@/lib/storage/user-store";
import { withLock } from "@/lib/events/lock";

type OverrideMap = Record<string, ProfileOverride>;

const OVERRIDES_FILE = "sage-contact-overrides.json";

function lockKey(username: string): string {
  return `contact-overrides:${username}`;
}

// ── Public API ────────────────────────────────────────────────────────────────
// All functions require `username` so each user's overrides are stored under
// DATA_DIR/users/<username>/sage-contact-overrides.json (isolated per user).

export async function getAllOverridesFromStore(username: string): Promise<OverrideMap> {
  return readUserStore<OverrideMap>(username, OVERRIDES_FILE, {});
}

export async function getOverrideFromStore(
  username: string,
  contactId: string
): Promise<ProfileOverride | undefined> {
  const all = await getAllOverridesFromStore(username);
  return all[contactId];
}

export async function setOverrideInStore(
  username: string,
  contactId: string,
  patch: ProfileOverride
): Promise<ProfileOverride> {
  return withLock(lockKey(username), async () => {
    const all = await readUserStore<OverrideMap>(username, OVERRIDES_FILE, {});
    const merged: ProfileOverride = { ...all[contactId], ...patch };
    all[contactId] = merged;
    await writeUserStore(username, OVERRIDES_FILE, all);
    return merged;
  });
}

export async function clearOverrideFromStore(username: string, contactId: string): Promise<void> {
  return withLock(lockKey(username), async () => {
    const all = await readUserStore<OverrideMap>(username, OVERRIDES_FILE, {});
    if (!all[contactId]) return;
    delete all[contactId];
    await writeUserStore(username, OVERRIDES_FILE, all);
  });
}
