/**
 * Server-side persistent store for AI-generated contact profile overrides.
 *
 * When Michael clicks "Generate profile with Basil" on a contact, the resulting
 * personality/whatMakesThemTick/watchOut fields are stored here rather than in
 * localStorage so:
 *   - The drafter (lib/events/drafter.ts) can use enriched profiles when
 *     composing replies, rather than falling back to the seed profile only.
 *   - Meeting prep can incorporate the latest AI read on an attendee.
 *   - The system prompt persona summaries can reflect current AI knowledge.
 *
 * Only fields regenerated by AI are overridden.  The base Contact record in
 * lib/contacts-data.ts remains the canonical source for everything else.
 */

import type { ProfileOverride } from "@/lib/contact-profile-overrides";
import { readStore, writeStore } from "@/lib/storage/persistent";
import { withLock } from "@/lib/events/lock";

type OverrideMap = Record<string, ProfileOverride>;

const OVERRIDES_FILE = "sage-contact-overrides.json";
const LOCK_KEY = "contact-overrides";

// ── Public API ────────────────────────────────────────────────────────────────

export async function getAllOverridesFromStore(): Promise<OverrideMap> {
  return readStore<OverrideMap>(OVERRIDES_FILE, {});
}

export async function getOverrideFromStore(
  contactId: string
): Promise<ProfileOverride | undefined> {
  const all = await getAllOverridesFromStore();
  return all[contactId];
}

export async function setOverrideInStore(
  contactId: string,
  patch: ProfileOverride
): Promise<ProfileOverride> {
  return withLock(LOCK_KEY, async () => {
    const all = await readStore<OverrideMap>(OVERRIDES_FILE, {});
    const merged: ProfileOverride = { ...all[contactId], ...patch };
    all[contactId] = merged;
    await writeStore(OVERRIDES_FILE, all);
    return merged;
  });
}

export async function clearOverrideFromStore(contactId: string): Promise<void> {
  return withLock(LOCK_KEY, async () => {
    const all = await readStore<OverrideMap>(OVERRIDES_FILE, {});
    if (!all[contactId]) return;
    delete all[contactId];
    await writeStore(OVERRIDES_FILE, all);
  });
}
