// ── WhatsApp one-shot snapshot ──
//
// Lifecycle of a single dump:
//   1. Session opens via Baileys — WhatsApp returns a QR code to scan
//   2. User scans from their phone → auth completes
//   3. The phone streams history (`messaging-history.set` events) to the socket
//   4. After a quiet window (history stops arriving) we save what we have
//   5. `sock.logout()` unlinks the device server-side + on the user's phone
//   6. Auth credentials get wiped from disk — next dump requires a fresh QR
//
// All state (auth dir, snapshot file, status file, signal index) is scoped per
// username so multiple users can import independently without cross-contamination.

import { promises as fs } from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { DATA_DIR as STORE_DATA_DIR } from "@/lib/storage/paths"; // ci-ok: importing canonical path constant from storage layer
import { readStore, writeStore, deleteStore } from "@/lib/storage/persistent";
import makeWASocket, {
  useMultiFileAuthState,
  fetchLatestBaileysVersion,
  DisconnectReason,
  Browsers,
  type WAMessage,
  type Chat,
  type Contact as WAContact,
} from "@whiskeysockets/baileys";
import QRCode from "qrcode";

export type DumpState =
  | "idle"
  | "awaiting_qr"
  | "authenticating"
  | "syncing"
  | "saving"
  | "disconnecting"
  | "done"
  | "error"
  | "cancelled";

export interface DumpStatus {
  state: DumpState;
  /** Unique identifier per import session — generated by startDump(). */
  jobId?: string;
  qrDataUrl?: string;
  startedAt?: string;
  /** ISO — when this job auto-expires (5 min after startedAt). */
  expiresAt?: string;
  finishedAt?: string;
  chatCount: number;
  messageCount: number;
  contactCount: number;
  error?: string;
  /** Soft progress hint for the UI — "pulled 42 chats so far" etc. */
  progressNote?: string;
}

/** Jobs that haven't reached done/error/cancelled within this window are expired. */
const JOB_TTL_MS = 5 * 60 * 1000; // 5 minutes

export interface SnapshotChat {
  id: string; // Baileys jid, e.g. "491234567890@s.whatsapp.net" or "groupid@g.us"
  name: string;
  isGroup: boolean;
  unreadCount?: number;
  lastMessageAt?: string; // ISO
  lastMessagePreview?: string;
  messageCount: number;
  messages: SnapshotMessage[];
}

export interface SnapshotMessage {
  id: string;
  fromMe: boolean;
  author?: string; // in groups, the participant jid
  authorName?: string;
  timestamp: string; // ISO
  text?: string;
  type:
    | "text"
    | "image"
    | "video"
    | "audio"
    | "document"
    | "sticker"
    | "voice"
    | "location"
    | "contact"
    | "system"
    | "other";
  /** Media caption or a short note about non-text content. */
  note?: string;
}

export interface SnapshotContact {
  id: string; // jid
  name?: string;
  pushName?: string;
  phoneNumber?: string;
  notify?: string;
}

export interface Snapshot {
  capturedAt: string;
  chatCount: number;
  messageCount: number;
  contactCount: number;
  chats: SnapshotChat[];
  contacts: SnapshotContact[];
  /** The linked account's own jid (useful for resolving fromMe). */
  meJid?: string;
  meName?: string;
}

// ── Compact signal index ──────────────────────────────────────────────────────
//
// The full whatsapp-snapshot.json can be large. The signal index is a
// stripped-down version (direct chats only, last N msgs) stored via writeStore
// so it survives cold starts. getWhatsAppSignalForContact falls back to it when
// the full snapshot is absent.

const SIGNAL_INDEX_FILE = "whatsapp-signal-index.json";
const SIGNAL_MAX_CHATS   = 40;
const SIGNAL_MAX_MSGS    = 6;
const SIGNAL_MAX_TEXT    = 80;

export interface SignalIndexChat {
  jid: string;   // user portion of JID, e.g. "447700900123"
  name: string;
  msgs: string[];// pre-formatted "[YYYY-MM-DD] speaker: text" lines
}

export interface SignalIndex {
  capturedAt: string;
  chats: SignalIndexChat[];
}

// ── Per-user path helpers ─────────────────────────────────────────────────────

/** Convert a username to a filesystem-safe directory component. */
function safeUser(username: string): string {
  // Lowercase first: usernames are case-insensitive, so all per-user paths agree.
  return username.toLowerCase().replace(/[^a-zA-Z0-9._-]/g, "_");
}

/** Subdirectory passed to readStore/writeStore for per-user files. */
function userSubdir(username: string): string {
  return `users/${safeUser(username)}`;
}

/** Absolute path to the per-user WhatsApp auth directory (filesystem only). */
function authDir(username: string): string {
  return path.join(STORE_DATA_DIR, "users", safeUser(username), "whatsapp-auth");
}

/** Absolute path to the per-user WhatsApp snapshot JSON file (filesystem only). */
function snapshotPath(username: string): string {
  return path.join(STORE_DATA_DIR, "users", safeUser(username), "whatsapp-snapshot.json");
}

// ── Per-user in-memory status bag ─────────────────────────────────────────────
//
// Stored on globalThis under a stable Symbol so it survives HMR in dev.
// A Map<username → GlobalBag> enables independent dumps per user.

const BAGS_KEY = Symbol.for("basil.whatsapp.bags");

interface GlobalBag {
  status: DumpStatus;
  running: boolean;
  /** Set by resetDump() to signal any running job to stop immediately. */
  cancelRequested: boolean;
  /** Active Baileys socket — stored so resetDump() can force-close it on cancel. */
  currentSocket?: ReturnType<typeof makeWASocket>;
}

function bag(username: string): GlobalBag {
  const g = globalThis as unknown as Record<symbol, Map<string, GlobalBag> | undefined>;
  if (!g[BAGS_KEY]) {
    g[BAGS_KEY] = new Map<string, GlobalBag>();
  }
  const bags = g[BAGS_KEY]!;
  if (!bags.has(username)) {
    bags.set(username, {
      status: { state: "idle", chatCount: 0, messageCount: 0, contactCount: 0 },
      running: false,
      cancelRequested: false,
    });
  }
  return bags.get(username)!;
}

// File key used to persist status across Vercel instances.
export const WHATSAPP_STATUS_FILE = "whatsapp-status.json";

/** Return true if a status represents an in-progress job that has passed TTL. */
function isExpired(s: DumpStatus): boolean {
  const terminal: DumpState[] = ["idle", "done", "error", "cancelled"];
  if (terminal.includes(s.state)) return false;
  if (!s.expiresAt) return false;
  return Date.now() > new Date(s.expiresAt).getTime();
}

/**
 * Return the in-memory status for a user.
 * If the job has passed its TTL the status is auto-transitioned to error so the
 * UI never shows "syncing" forever after a crashed Vercel function.
 */
export function getStatus(username: string): DumpStatus {
  const b = bag(username);
  if (isExpired(b.status)) {
    const expired: DumpStatus = {
      ...b.status,
      state: "error",
      error: "Import timed out — the Vercel function was likely recycled. Start again.",
      finishedAt: new Date().toISOString(),
    };
    b.status = expired;
    // Persist the expiry so other instances also see it.
    void writeStore<DumpStatus>(WHATSAPP_STATUS_FILE, expired, userSubdir(username));
  }
  return b.status;
}

function setStatus(username: string, patch: Partial<DumpStatus>): void {
  const b = bag(username);
  b.status = { ...b.status, ...patch };
  // Persist to file store so status polls landing on any Vercel instance
  // can return the real state (not the stale "idle" from Instance B).
  void writeStore<DumpStatus>(WHATSAPP_STATUS_FILE, b.status, userSubdir(username));
}

/**
 * Read the persisted status file for a user.  Applies the same expiry check as
 * getStatus() so callers on any Vercel instance see consistent state.
 * Returns null if no persisted status exists.
 */
export async function readPersistedStatus(username: string): Promise<DumpStatus | null> {
  const sub = userSubdir(username);
  let s: DumpStatus | null = null;
  try {
    s = await readStore<DumpStatus | null>(WHATSAPP_STATUS_FILE, null, sub);
  } catch {
    return null;
  }
  if (!s) return null;
  if (isExpired(s)) {
    const expired: DumpStatus = {
      ...s,
      state: "error",
      error: "Import timed out — the Vercel function was likely recycled. Start again.",
      finishedAt: new Date().toISOString(),
    };
    // Write the expiry so all subsequent reads are consistent.
    void writeStore<DumpStatus>(WHATSAPP_STATUS_FILE, expired, sub);
    return expired;
  }
  return s;
}

/**
 * Build a compact signal index from a Snapshot and persist it via writeStore.
 */
export async function persistSignalIndex(username: string, snapshot: Snapshot): Promise<void> {
  const direct = snapshot.chats
    .filter((c) => !c.isGroup)
    .sort((a, b) => {
      const ta = a.lastMessageAt ? new Date(a.lastMessageAt).getTime() : 0;
      const tb = b.lastMessageAt ? new Date(b.lastMessageAt).getTime() : 0;
      return tb - ta;
    })
    .slice(0, SIGNAL_MAX_CHATS);

  const chats: SignalIndexChat[] = direct.map((chat) => {
    const recent = [...chat.messages]
      .filter((m) => !!m.text)
      .slice(-SIGNAL_MAX_MSGS);
    const msgs = recent.map((m) => {
      const speaker = m.fromMe ? username : chat.name;
      const text = (m.text ?? "").slice(0, SIGNAL_MAX_TEXT);
      return `[${m.timestamp?.slice(0, 10) ?? ""}] ${speaker}: ${text}`;
    });
    return { jid: chat.id.split("@")[0], name: chat.name, msgs };
  });

  const index: SignalIndex = { capturedAt: snapshot.capturedAt, chats };
  await writeStore<SignalIndex>(SIGNAL_INDEX_FILE, index, userSubdir(username), { durability: "strong" });
  console.log(`[whatsapp] Wrote signal index for ${username}: ${chats.length} chats`);
}

export async function getSnapshot(username: string): Promise<Snapshot | null> {
  // Try L1 (/tmp) first — fastest path, always warm on the instance that wrote it.
  try {
    const raw = await fs.readFile(snapshotPath(username), "utf8");
    return JSON.parse(raw) as Snapshot;
  } catch {
    // L1 miss (cold start or different instance) — fall back to Blob (L2).
    return readStore<Snapshot | null>("whatsapp-snapshot.json", null, userSubdir(username));
  }
}

export async function deleteSnapshot(username: string): Promise<void> {
  // Remove from both L1 and L2.
  try { await fs.unlink(snapshotPath(username)); } catch { /* ignore */ }
  await deleteStore("whatsapp-snapshot.json", userSubdir(username));
}

async function wipeAuthDir(username: string): Promise<void> {
  try {
    await fs.rm(authDir(username), { recursive: true, force: true });
  } catch {
    /* best effort */
  }
}

/**
 * Extract the sender's push name from an inbound message and write it back
 * into contactsById so that contacts without address-book names still get a
 * display name in the snapshot.
 */
function harvestPushName(
  m: WAMessage,
  contactsById: Map<string, WAContact>
): void {
  if (!m.pushName || m.key.fromMe) return;
  const senderJid = m.key.participant || m.key.remoteJid;
  if (!senderJid) return;
  const existing = contactsById.get(senderJid);
  if (existing) {
    if (!existing.notify) {
      contactsById.set(senderJid, { ...existing, notify: m.pushName });
    }
  } else {
    contactsById.set(senderJid, { id: senderJid, notify: m.pushName });
  }
}

function extractText(msg: WAMessage): { text?: string; type: SnapshotMessage["type"]; note?: string } {
  const m = msg.message;
  if (!m) return { type: "system", note: "(empty/system)" };
  if (m.conversation) return { text: m.conversation, type: "text" };
  if (m.extendedTextMessage?.text)
    return { text: m.extendedTextMessage.text, type: "text" };
  if (m.imageMessage)
    return { type: "image", note: m.imageMessage.caption || "(image)" };
  if (m.videoMessage)
    return { type: "video", note: m.videoMessage.caption || "(video)" };
  if (m.audioMessage)
    return {
      type: m.audioMessage.ptt ? "voice" : "audio",
      note: m.audioMessage.ptt ? "(voice note)" : "(audio)",
    };
  if (m.documentMessage)
    return { type: "document", note: m.documentMessage.fileName || "(document)" };
  if (m.stickerMessage) return { type: "sticker", note: "(sticker)" };
  if (m.locationMessage) return { type: "location", note: "(location)" };
  if (m.contactMessage || m.contactsArrayMessage)
    return { type: "contact", note: "(contact card)" };
  return { type: "other", note: "(unsupported message type)" };
}

function jidToPhone(jid: string): string | undefined {
  const m = jid.match(/^(\d+)@/);
  return m ? `+${m[1]}` : undefined;
}

function chatDisplayName(
  chat: Chat,
  contacts: Map<string, WAContact>
): string {
  if (chat.name) return chat.name;
  const id = chat.id ?? "";
  if (!id) return "Unknown chat";
  const contact = contacts.get(id);
  if (contact?.name) return contact.name;
  if (contact?.notify) return contact.notify;
  if (id.endsWith("@g.us")) return "Group chat";
  return jidToPhone(id) || id;
}

const QUIET_WINDOW_MS = 20_000;
const MAX_WAIT_MS = 240_000;

/**
 * Run one snapshot job for the given user. Safe to call while a job is running
 * (returns immediately). Returns a task callback for `after()` so Vercel keeps
 * the function instance alive for the full dump duration.
 */
export function startDump(username: string): { alreadyRunning: boolean; jobId: string; task: () => Promise<void> } {
  const b = bag(username);
  if (b.running) {
    return { alreadyRunning: true, jobId: b.status.jobId ?? "", task: () => Promise.resolve() };
  }
  b.running = true;

  const jobId = randomUUID();
  const now = new Date();
  setStatus(username, {
    state: "awaiting_qr",
    jobId,
    qrDataUrl: undefined,
    startedAt: now.toISOString(),
    expiresAt: new Date(now.getTime() + JOB_TTL_MS).toISOString(),
    finishedAt: undefined,
    error: undefined,
    chatCount: 0,
    messageCount: 0,
    contactCount: 0,
    progressNote: "Starting session…",
  });

  const task = () => (async () => {
    const b = bag(username);
    b.cancelRequested = false;
    try {
      await wipeAuthDir(username);
      if (b.cancelRequested) { b.running = false; return; }
      await fs.mkdir(authDir(username), { recursive: true });
      const { state, saveCreds } = await useMultiFileAuthState(authDir(username));
      const { version } = await fetchLatestBaileysVersion();

      const chatsById = new Map<string, Chat>();
      const messagesByChat = new Map<string, Map<string, WAMessage>>();
      const contactsById = new Map<string, WAContact>();

      let lastHistoryAt = 0;
      let historyCompleted = false;
      let meJid: string | undefined;
      let meName: string | undefined;

      let currentSock: ReturnType<typeof makeWASocket>;
      let reconnectAttempts = 0;
      const MAX_RECONNECTS = 4;

      const connectSocket = () => {
        if (b.cancelRequested) return;
        const sock = makeWASocket({
          version,
          auth: state,
          browser: Browsers.macOS("Basil"),
          printQRInTerminal: false,
          syncFullHistory: true,
          markOnlineOnConnect: false,
          qrTimeout: 60_000,
          connectTimeoutMs: 45_000,
        });
        currentSock = sock;
        b.currentSocket = sock;

        sock.ev.on("creds.update", saveCreds);

        sock.ev.on("connection.update", async (u) => {
          if (b.cancelRequested) return;
          const { connection, qr, lastDisconnect } = u;
          if (qr) {
            try {
              const dataUrl = await QRCode.toDataURL(qr, { margin: 1, width: 320 });
              setStatus(username, { state: "awaiting_qr", qrDataUrl: dataUrl });
            } catch {
              /* ignore QR render failures */
            }
          }
          if (connection === "connecting") {
            if (b.status.state === "awaiting_qr" && b.status.qrDataUrl) {
              setStatus(username, {
                state: "authenticating",
                qrDataUrl: undefined,
                progressNote: "QR scanned — authenticating…",
              });
            }
          }
          if (connection === "open") {
            reconnectAttempts = 0;
            meJid = sock.user?.id;
            meName = sock.user?.name || undefined;
            setStatus(username, {
              state: "syncing",
              qrDataUrl: undefined,
              progressNote: "Linked. Waiting for WhatsApp to push your history…",
            });
            lastHistoryAt = Date.now();
          }
          if (connection === "close") {
            const code = (lastDisconnect?.error as { output?: { statusCode?: number } } | undefined)?.output?.statusCode;

            if (code === DisconnectReason.restartRequired && reconnectAttempts < MAX_RECONNECTS && !b.cancelRequested) {
              reconnectAttempts++;
              console.log(`[whatsapp] restartRequired — reconnecting (${reconnectAttempts}/${MAX_RECONNECTS})`);
              setTimeout(() => connectSocket(), 1_500);
              return;
            }

            if (
              !historyCompleted &&
              code !== DisconnectReason.loggedOut &&
              code !== DisconnectReason.connectionClosed
            ) {
              setStatus(username, {
                state: "error",
                error: `Connection closed: ${code ?? "unknown"}`,
                finishedAt: new Date().toISOString(),
              });
              bag(username).running = false;
            }
          }
        });

        sock.ev.on("messaging-history.set", (evt) => {
          if (b.cancelRequested) return;
          const { chats, messages, contacts, isLatest } = evt;
          for (const c of chats) {
            if (c.id) chatsById.set(c.id, c);
          }
          for (const ct of contacts) contactsById.set(ct.id, ct);
          for (const m of messages) {
            const key = m.key;
            if (!key?.remoteJid || !key.id) continue;
            if (!messagesByChat.has(key.remoteJid)) {
              messagesByChat.set(key.remoteJid, new Map());
            }
            messagesByChat.get(key.remoteJid)!.set(key.id, m);
            harvestPushName(m, contactsById);
          }
          lastHistoryAt = Date.now();
          const totalMsgs = [...messagesByChat.values()].reduce(
            (n, m) => n + m.size,
            0
          );
          setStatus(username, {
            state: "syncing",
            chatCount: chatsById.size,
            messageCount: totalMsgs,
            contactCount: contactsById.size,
            progressNote: `Pulled ${chatsById.size} chat(s), ${totalMsgs} message(s) so far…`,
          });
          if (isLatest) {
            historyCompleted = true;
          }
        });

        sock.ev.on("messages.upsert", ({ messages }) => {
          if (b.cancelRequested) return;
          for (const m of messages) {
            const key = m.key;
            if (!key?.remoteJid || !key.id) continue;
            if (!messagesByChat.has(key.remoteJid)) {
              messagesByChat.set(key.remoteJid, new Map());
            }
            messagesByChat.get(key.remoteJid)!.set(key.id, m);
            harvestPushName(m, contactsById);
          }
          lastHistoryAt = Date.now();
        });
      };

      connectSocket();

      const start = Date.now();
      await new Promise<void>((resolve) => {
        const interval = setInterval(() => {
          if (b.cancelRequested) {
            clearInterval(interval);
            resolve();
            return;
          }
          const now = Date.now();
          const elapsed = now - start;
          if (historyCompleted && chatsById.size > 0) {
            clearInterval(interval);
            resolve();
            return;
          }
          if (elapsed > MAX_WAIT_MS) {
            clearInterval(interval);
            resolve();
            return;
          }
          if (chatsById.size === 0 && lastHistoryAt === 0) {
            const waitSecs = Math.floor(elapsed / 1000);
            const maxSecs  = Math.floor(MAX_WAIT_MS / 1000);
            if (b.status.state === "syncing") {
              setStatus(username, {
                progressNote: `Waiting for WhatsApp to push history… (${waitSecs}s / ${maxSecs}s max)`,
              });
            }
          }
          if (
            lastHistoryAt > 0 &&
            now - lastHistoryAt > QUIET_WINDOW_MS &&
            chatsById.size > 0
          ) {
            clearInterval(interval);
            resolve();
          }
        }, 1500);
      });

      if (b.cancelRequested) {
        try { await currentSock!.logout(); } catch { /* ignore */ }
        await wipeAuthDir(username);
        return;
      }

      if (chatsById.size === 0) {
        setStatus(username, {
          state: "error",
          error: "WhatsApp linked but sent no chat history. This usually means the sync timed out before data arrived. Click Re-import and try again — scan the QR quickly once it appears.",
          finishedAt: new Date().toISOString(),
        });
        bag(username).running = false;
        try { await currentSock!.logout(); } catch { /* ignore */ }
        await wipeAuthDir(username);
        return;
      }

      setStatus(username, {
        state: "saving",
        progressNote: "Packing snapshot…",
      });

      const chatsOut: SnapshotChat[] = [];
      for (const [id, chat] of chatsById) {
        const msgMap = messagesByChat.get(id) || new Map();
        const msgs = [...msgMap.values()]
          .sort((a, b) => {
            const ta = Number(a.messageTimestamp || 0);
            const tb = Number(b.messageTimestamp || 0);
            return ta - tb;
          })
          .map<SnapshotMessage>((m) => {
            const { text, type, note } = extractText(m);
            const ts = Number(m.messageTimestamp || 0);
            const authorJid = m.key.participant || m.key.remoteJid || undefined;
            const authorName = authorJid
              ? contactsById.get(authorJid)?.name ||
                contactsById.get(authorJid)?.notify ||
                jidToPhone(authorJid)
              : undefined;
            return {
              id: m.key.id!,
              fromMe: !!m.key.fromMe,
              author: authorJid,
              authorName,
              timestamp: ts ? new Date(ts * 1000).toISOString() : "",
              text,
              type,
              note,
            };
          });

        const last = msgs[msgs.length - 1];
        chatsOut.push({
          id,
          name: chatDisplayName(chat, contactsById),
          isGroup: id.endsWith("@g.us"),
          unreadCount: chat.unreadCount || 0,
          lastMessageAt: last?.timestamp,
          lastMessagePreview: last?.text?.slice(0, 160) || last?.note,
          messageCount: msgs.length,
          messages: msgs,
        });
      }

      chatsOut.sort((a, b) => {
        const ta = a.lastMessageAt ? new Date(a.lastMessageAt).getTime() : 0;
        const tb = b.lastMessageAt ? new Date(b.lastMessageAt).getTime() : 0;
        return tb - ta;
      });

      const contactsOut: SnapshotContact[] = [...contactsById.values()].map(
        (c) => ({
          id: c.id,
          name: c.name,
          pushName: c.notify,
          notify: c.notify,
          phoneNumber: jidToPhone(c.id),
        })
      );

      const totalMsgs = chatsOut.reduce((n, c) => n + c.messageCount, 0);
      const snapshot: Snapshot = {
        capturedAt: new Date().toISOString(),
        chatCount: chatsOut.length,
        messageCount: totalMsgs,
        contactCount: contactsOut.length,
        chats: chatsOut,
        contacts: contactsOut,
        meJid,
        meName,
      };

      // writeStore with durability:"strong" awaits the Blob write before
      // returning — the snapshot is durable before we proceed to logout.
      await writeStore("whatsapp-snapshot.json", snapshot, userSubdir(username), { durability: "strong" });

      // persistSignalIndex also uses strong durability internally.
      await persistSignalIndex(username, snapshot);

      setStatus(username, {
        state: "disconnecting",
        chatCount: snapshot.chatCount,
        messageCount: snapshot.messageCount,
        contactCount: snapshot.contactCount,
        progressNote: "Snapshot saved. Unlinking device…",
      });

      try {
        await currentSock!.logout();
      } catch {
        /* network may already be closed */
      }
      await wipeAuthDir(username);

      setStatus(username, {
        state: "done",
        finishedAt: new Date().toISOString(),
        progressNote: `Imported ${snapshot.chatCount} chat(s), ${snapshot.messageCount} message(s). Device unlinked.`,
      });
    } catch (e) {
      if (!b.cancelRequested) {
        console.error(`[whatsapp dump] failed for ${username}:`, e);
        setStatus(username, {
          state: "error",
          error: e instanceof Error ? e.message : "Unknown error",
          finishedAt: new Date().toISOString(),
        });
      }
      await wipeAuthDir(username);
    } finally {
      b.running = false;
      b.currentSocket = undefined;
      if (b.cancelRequested) {
        b.cancelRequested = false;
        b.status = { state: "idle", chatCount: 0, messageCount: 0, contactCount: 0 };
      }
    }
  })();

  return { alreadyRunning: false, jobId, task };
}

export async function resetDump(username: string): Promise<void> {
  const b = bag(username);
  b.cancelRequested = true;

  // Force-close the socket immediately on this instance.
  if (b.currentSocket) {
    try { b.currentSocket.end(undefined); } catch { /* socket may already be closed */ }
    b.currentSocket = undefined;
  }

  // Write a durable "cancelled" status so that:
  //   (a) other Vercel instances that poll status also see the job is done
  //   (b) the next page load shows "idle" rather than a stale "syncing"
  const cancelledStatus: DumpStatus = {
    state: "cancelled",
    jobId: b.status.jobId,
    chatCount: 0,
    messageCount: 0,
    contactCount: 0,
    finishedAt: new Date().toISOString(),
    progressNote: "Cancelled by user.",
  };
  b.status = cancelledStatus;
  // Write with strong durability so the cancelled state is durable before
  // the caller's response is sent.
  await writeStore<DumpStatus>(WHATSAPP_STATUS_FILE, cancelledStatus, userSubdir(username), { durability: "strong" });

  await wipeAuthDir(username);

  // Reset in-memory to idle now that persistence is written.
  b.status = { state: "idle", chatCount: 0, messageCount: 0, contactCount: 0 };
  if (!b.running) {
    b.cancelRequested = false;
  }
}

/**
 * Returns up to `limit` recent messages from the WhatsApp snapshot that
 * belong to a specific person — for use as personality-profiling signal.
 *
 * On Vercel cold starts the full snapshot isn't available (large file).
 * Falls back to the compact signal index which IS persisted via writeStore.
 */
export async function getWhatsAppSignalForContact(
  username: string,
  name: string,
  phone?: string,
  limit = 40
): Promise<string[]> {
  const nameLower   = name.trim().toLowerCase();
  const firstName   = nameLower.split(/\s+/)[0];
  const phoneDigits = phone ? phone.replace(/\D/g, "").slice(-9) : null;

  // ── Path A: full snapshot (same instance as dump, or warm local dev) ─────
  const snapshot = await getSnapshot(username);
  if (snapshot) {
    const lines: string[] = [];
    for (const chat of snapshot.chats) {
      const chatNameLower = (chat.name ?? "").toLowerCase();
      const chatJidPhone  = chat.id.split("@")[0].replace(/\D/g, "");

      const isDirect =
        !chat.isGroup &&
        (chatNameLower.includes(nameLower) ||
          (firstName.length >= 3 && chatNameLower.includes(firstName)) ||
          (phoneDigits && chatJidPhone.endsWith(phoneDigits)));

      for (const msg of chat.messages) {
        if (!msg.text) continue;
        if (isDirect) {
          const speaker = msg.fromMe ? username : (chat.name || "Them");
          lines.push(`[${msg.timestamp?.slice(0, 10)}] ${speaker}: ${msg.text}`);
        } else if (chat.isGroup) {
          const authorLower = (msg.authorName ?? "").toLowerCase();
          if (
            authorLower.includes(nameLower) ||
            (firstName.length >= 3 && authorLower.includes(firstName))
          ) {
            lines.push(`[${msg.timestamp?.slice(0, 10)}] ${msg.authorName} (in ${chat.name}): ${msg.text}`);
          }
        }
        if (lines.length >= limit) break;
      }
      if (lines.length >= limit) break;
    }
    return lines;
  }

  // ── Path B: compact signal index (Vercel cold-start fallback) ───────────
  const index = await readStore<SignalIndex | null>(SIGNAL_INDEX_FILE, null, userSubdir(username));
  if (!index) {
    console.log(`[whatsapp] No signal for "${name}" (user ${username}) — snapshot and signal index both absent`);
    return [];
  }

  const lines: string[] = [];
  for (const chat of index.chats) {
    const chatNameLower = chat.name.toLowerCase();
    const chatJidPhone  = chat.jid.replace(/\D/g, "");

    const matches =
      chatNameLower.includes(nameLower) ||
      (firstName.length >= 3 && chatNameLower.includes(firstName)) ||
      (phoneDigits && chatJidPhone.endsWith(phoneDigits));

    if (matches) {
      for (const line of chat.msgs) {
        lines.push(line);
        if (lines.length >= limit) break;
      }
    }
    if (lines.length >= limit) break;
  }
  console.log(`[whatsapp] Signal index lookup for "${name}" (user ${username}): ${lines.length} lines`);
  return lines;
}
